name: user_repository
description: Dart package which manages the user domain.
publish_to: none
uses-material-design: true

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  json_annotation: ^4.4.0
  http: ^0.13.4
  meta: ^1.7.0
  very_good_analysis: ^2.0.0
  interest_repository:
    path: ../interest_repository
  connect_repository:
    path: ../connect_repository
  cache:
    path: ../cache
  constants:
    path: ../constants


dev_dependencies:
  flutter_test:
    sdk: flutter
  coverage: ^1.0.3
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  mocktail: ^0.2.0
  test: ^1.16.4


