name: constants
description: A simple in storage for constants
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.17.11
  very_good_analysis: ^2.3.0